name: push-docker-and-webhook

on:
 push:
  branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
          docker build -t $target_docker_image .
          docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
          docker push $target_docker_image
      env:
          target_docker_image: ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_NAMESPACE}}/rapclient:1.0.2

    - name: success
      run: |
        echo "success"
